### ISSUE TITLE
Default PTI configuration is unexpected

### ISSUE THREAD

**Issue by dashmage** [canonical/charm-sysconfig#27]
Just installing sysconfig the first time without particular charm configuration; the cmdline gets extended with pti=off.
This may or may not be what the user expects, but it does change the default configuration.
It's coming from how the template gets rendered:
https://git.launchpad.net/charm-sysconfig/tree/src/templates/grub.j2#n32
and https://git.launchpad.net/charm-sysconfig/tree/src/config.yaml#n75

Would be better to have to change the config option in case you decide to need the config to be changed.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-01-29T15:52:25Z
 * owner: [gabor.meszaros](https://launchpad.net/~gabor.meszaros)
 * assignee: [None](https://launchpad.net/~None)
 * duplicate of: #17
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1913764)

**Comment by aieri** [comment]
closing as resolved in #17
