### ISSUE TITLE
Blocked status on initial deployment due to grub

### ISSUE THREAD

**Issue by dashmage** [canonical/charm-sysconfig#40]
Deploying charm-sysconfig with ubuntu 22.04 results in the charm going into blocked status with the message: `update-grub and reboot required. Changes in /etc/default/grub.d/90-sysconfig.cfg`. But the `90-sysconfig.cfg` file does not contain any specific config apart from some comments.

Upon SSH-ing into the unit, it looked like there was a difference between `/etc/boot/grub.cfg` and the grub config rendered using `grub-mkconfig` (which the charm uses to check whether there were any changes so it can notify for a reboot). 

Diff output: https://pastebin.ubuntu.com/p/DPCyQK55mj/

A similar problem had been resolved with the systemd conf file here: [bug report](https://bugs.launchpad.net/charm-sysconfig/+bug/2012581), [MP](https://code.launchpad.net/~dashmage/charm-sysconfig/+git/charm-sysconfig/+merge/450413).

From the diff, we can see that there is somehow a difference in the way the root fs is being referenced (with the `LABEL` or with `UUID`).

**Comment by aieri** [comment]
given that sysconfig does not let you alter the `root=` kernel parameter, perhaps we should not include in the comparison
